### ISSUE TITLE
.split on undefined causes a crash

### ISSUE THREAD

**Issue by ManuelFeller** [BIX-Digital/directus-version-control-changelog#3]
It can happen that the trigger ends up in an error as below:

TypeError: Cannot read properties of undefined (reading 'split')
    at Function.formatLatestChanges (/directus/extensions/hooks/version-control-changelog/index.js:8:8352)
    at Bi.triggerProcessor (/directus/extensions/hooks/version-control-changelog/index.js:8:19511)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

The reason still needs to be investigated, but the guess is that the system cannot handle formatting of a NULL value in the previous change log data yet (as this appears on a system that never had any content in that field before)

**Comment by ManuelFeller** [comment]
This trigger leads to Directus then no longer responding to requests, needing a restart of the CMS server. So for now this issue block proper usage of the extension

**Comment by ManuelFeller** [comment]
The first thought seems to be wrong
- the content is already available
- the previous content of the field is not used at all

Further investigation on the affected system is needed

**Comment by ManuelFeller** [comment]
Analysis of the code has shown that the error is happening at https://github.com/BIX-Digital/directus-version-control-changelog/blob/bugfix/split-on-undefined/src/core/ChangelogFormatter.ts#L17 -> is seems that `userChangelog` is `undefined`.

It is confirmed that neither the branch nor the file exist in the target repository yet, so this kind of makes sense.

**Comment by ManuelFeller** [comment]
The actual culprit is https://github.com/BIX-Digital/directus-version-control-changelog/blob/bugfix/split-on-undefined/src/core/ChangelogWriter.ts#L102 -> in there it uses a hardcoded field name (`changes`) when looking for the changes content in `event.payload`.

This needs
- to be mapped to the configured field name
- more error tolerant access to that field (as in some setups changes may happen in fields that we're not interested in, not in the one where we expect them)
